---

- hosts: web_servers
  become: true
  tasks:
    - name: Install lib_pam 
      apt:
        name: libpam-ssh-agent-auth
        state: latest
    - name: Configurer .bashrc
        lineinfile:
        dest: /home/costamagna/.bashrc
        insertafter: EOF
        line: 'eval $(ssh-agent)'
    - name: Configurer bash logout
        lineinfile:
        dest: /home/costamagna/.bash_logout
        insertafter: EOF
        line: 'killall ssh-agent'
