---

- hosts: web_servers
  become: true
  tasks:
    - name: Install lib_pam 
      apt:
        name: libpam-ssh-agent-auth
        state: latest
    - name: Configurer .bashrc
      lineinfile:
        path: /home/test/.bashrc
        insertafter: EOF
        line: 'eval $(ssh-agent)'
        create: yes
    - name: Configurer bash logout
      lineinfile:
        path: /home/test/.bash_logout
        insertafter: EOF
        line: 'killall ssh-agent'
        create: yes
