---

- hosts: web_servers
  become: true
  tasks:
    - name: Install lib_pam 
      apt:
        name: libpam-ssh-agent-auth
        state: latest
    - name: sudo
      lineinfile:
        path: /etc/pam.d/sudo
        insertafter: (#%)
        line: 'auth sufficient pam_ssh_agent_auth.so file=/etc/security/authorized_keys'
    - name: Config sudoers
      lineinfile:
        path: /etc/sudoers
        insertbefore: ^\w 
        line: 'Defaults env_keep += SSH_AUTH_SOCK'
    - name: Configurer .bashrc
      lineinfile:
        path: /home/test/.bashrc
        insertafter: EOF
        line: 'eval $(ssh-agent)'
    - name: Configurer bash logout
      lineinfile:
        path: /home/test/.bash_logout
        insertafter: EOF
        line: 'killall ssh-agent'
